### ISSUE TITLE
How to abort the SMS Receiver API

### ISSUE THREAD

**Issue by manishbisht** [samuelgoto/WebOTP#14]
Is there an option to abort `sms.receive` ?

**Comment by samuelgoto** [comment]
It is a bit hidden in the spec, but there is one affordance to abort:

https://github.com/samuelgoto/WebOTP/blob/master/explainer.md#spec

```js
let abort = new AbortController();
setTimeout(() => {
  // abort after two minutes
  abort.abort();
}, 2 * 60 * 1000);
  
try {
  let {content} = await navigator.sms.receive(abort);
} catch (e) {
  // deal with errors
}
```

Feel free to re-open if that's insufficient.
