### ISSUE TITLE
Localize For:

### ISSUE THREAD

**Issue by eduardosada** [samuelgoto/WebOTP#8]
I can't implement the current spec on SMS in spanish. It would be nice to have the next SMS format instead:

```
123456 es tu código OTP

http://localhost/?otp=123456&EvsSSj4C6vl
```

Where the OTP is the first number appearing in the SMS message and the origin is the last url in the SMS message.

**Comment by samuelgoto** [comment]
The latest formulation doesn't have any human-readable strings which we change to make it more localizable.

https://github.com/samuelgoto/WebOTP/blob/master/explainer.md#formatting

```
Your OTP is: 123ABC78.
@example.com #123ABC78
```

Resolving, feel free to re-open if you feel it doesn't do justice to localization.

**Comment by eduardosada** [comment]
I'm sorry I think I'm not getting you. The format says "Your OTP is:" which is written in English. Are you saying that you won't change that format or that it's not necessary to change it because that part is not taken into account when parsing the SMS.

**Comment by samuelgoto** [comment]
I'm saying that the part of this message that computers will be reading will be the second line:

```
Your OTP is: 123ABC78.
@example.com #123ABC78
```

Which is this:

```
@example.com #123ABC78
```

That is

```
You can write whatever you want here in whatever language as long as it fits in the message
and the following line is kept:

@example.com #123ABC78
```

Makes sense?

**Comment by eduardosada** [comment]
Thank you so much for taking the trouble to explain it to me. You have been of great help. 👏
